// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkavfseimceqfypdazpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprYXZmc2VpbWNlcWZ5cGRhenBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjMzMzAsImV4cCI6MjA2NTQ5OTMzMH0.DuSvfwey5Gtsq-BytHQ9pmmvarulOZHCJ-Mq-hwz388";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);